### ISSUE TITLE
issue with volume

### ISSUE THREAD

**Issue by peterd550** [dray-cyber/googlecontroller#9]
I get this error when I change the volume
AttributeError: 'str' object has no attribute 'cast_type'
Traceback (most recent call last):
  File "/home/scripts/ghome_volume.py", line 20, in <module>
    castdevice = pychromecast.Chromecast(ip)
  File "/home/busybox/.local/lib/python3.7/site-packages/pychromecast/__init__.py", line 271, in __init__
    if not cast_info.cast_type:
AttributeError: 'str' object has no attribute 'cast_type'
Traceback (most recent call last):
  File "/home/scripts/ghome_volume.py", line 20, in <module>
    castdevice = pychromecast.Chromecast(ip)
  File "/home/busybox/.local/lib/python3.7/site-packages/pychromecast/__init__.py", line 271, in __init__
    if not cast_info.cast_type:
AttributeError: 'str' object has no attribute 'cast_type'

asn1crypto==0.24.0
casttube==0.2.1
certifi==2021.10.8
charset-normalizer==2.0.12
cryptography==2.6.1
entrypoints==0.3
googlecontroller==6
idna==3.3
ifaddr==0.1.7
keyring==17.1.1
keyrings.alt==3.1.1
Mako==1.0.7
Markdown==3.0.1
MarkupSafe==1.1.0
protobuf==3.19.4
PyChromecast==10.2.3
pycrypto==2.6.1
Pygments==2.3.1
PyGObject==3.30.4
pyngrok==5.1.0
pyxdg==0.25
PyYAML==3.13
requests==2.27.1
SecretStorage==2.3.1
six==1.12.0
urllib3==1.26.8
zeroconf==0.38.3

**Comment by peterd550** [comment]
Will this issue be fixed soon?

**Comment by peterd550** [comment]
Has this issue been resolved?

I'm need to update my docker containers and I can't as my old version's are erroring and if I just run my pip installs it still has an issue.

**Comment by peterd550** [comment]
The old versions are working with debian 10 but not with debian 11
